In [1]:
import numpy as np

### Problem 1: Find Minimum and Maximum in Array

In [3]:
def maxmin(arr):
    max_val = arr[0]
    min_val = arr[0]
    for i in range(1,len(arr)):
        if max_val < arr[i]:
            max_val = arr[i]
        if min_val > arr[i]:
            min_val = arr[i]
    print(max_val)
    print(min_val)
    
maxmin([1,6,4,5,8])

8
1


### Problem 2: Remove Duplicates from Sorted Array

In [12]:
def remove(arr):
    k = 1
    for i in range (1,len(arr)):
        if arr[i] != arr[i-1]:
            arr[k] = arr[i]
            k=k+1
    print(arr[0:k])
    
remove([1,1,1,2,2,3,4,5,6,7,7,7])
            
            

[1, 2, 3, 4, 5, 6, 7]


### Problem 3: Matrix Transposition

In [28]:
def transpose(arr):
    return arr.T
    
mat= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"original matrix \n {mat}")
transposed_mat = transpose(mat)
print(f"transpose \n {transposed_mat}")
    

original matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


### Problem 4: Fibonacci Sequence

In [32]:
def fibonacci(n):
    fib = [0,1]
    while len(fib) < n:
        fib.append(fib[-1] + fib[-2])
    return fib
    
    
fibonacci(8)

[0, 1, 1, 2, 3, 5, 8, 13]

In [33]:
def fibonacci(n):
    fib = [0,1]
    for i in range(2,n):
        fib.append(fib[-1] + fib[-2])
    return fib
    
    
fibonacci(8)

[0, 1, 1, 2, 3, 5, 8, 13]

### Problem 5: Two sum

In [37]:
def two_sum(arr, x):
    for i in range(len(arr)-1):
        for j in range(i+1,len(arr)):
            if x-arr[i] == arr[j]:
                return True
    return False

two_sum([1,2,5,6,3],11)

True

In [5]:
def two_sum1(arr,x):
    i=0
    j = len(arr)-1
    arr.sort()
    while (i<j):
        sum = arr[i]+arr[j]
        if (sum<x):
            i=i+1
        elif (sum>x):
            j=j-1
        else:
            return True
    return False

two_sum1([1,2,5,6,3],11)

True

In [6]:
two_sum1([1,2,5,6,3],12)

False

In [38]:
two_sum([1,2,5,6,3],12)

False

### Problem 6: Double-base Palindromes: 
The decimal number, 58510=10010010012 (binary), is palindromic in both base 10 and base 2. Find the sum of all four digit numbers, which are palindromic in base 10 and base 2. Note that both in base 10 and base 2, the palindromic number, should not
include leading zeros.

In [17]:
import time

In [8]:
def int_palin(n):
    sum = 0
    i=n
    while i>0:
        dig = i%10
        sum = sum*10 + dig
        i=i//10
    if sum == n:
        return True
    else:
        return False

int_palin(111)

True

In [9]:
def bool_palin(n):
    num = bin(n)[2:]
    if num == num[::-1]: #slicing
        return True
    return False

bool_palin(63)

True

In [36]:
def check():
    sum = 0
    begin = time.time()
    for i in range(1000,10000):
        if int_palin(i) and bool_palin(i):
            sum = sum + i
            print(i)
    end = time.time()
    print(end-begin)
    return sum

check()

7447
9009
0.023032426834106445


16456

In [23]:
def ispalin(n):
    return n==n[::-1]

def doublepalin():
    begin=time.time()
    sum=0
    for i in range (1000,10000):
        if ispalin(str(i)) and ispalin(bin(i)[2:]):
            sum = sum + i
    end = time.time()
    print(end-begin)
    return sum

t=doublepalin()
t

0.015512704849243164


16456

In [ ]:
#list comprehension will simplify this
#will implement conversion on all the elements at once